[project]
name = "templates"
version = "4.1.0"
description = "Template engine for variable substitution in plain markdown files"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.0.0",
]

[tool.uv.sources]
storage = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["templates"]